org: elatedmule
console: true

plugins:
  - serverless-webpack

service: serverless-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x



functions:
  firstLambda:
    handler: functions/firstLambda.handler

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore